MODULO 2/djangop/francysbeautykosmetik/urls.py
from django.contrib import admin
from django.urls import path
from loanapp.views import * #el* es para llamar a todas

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    path('usuario/registrar/', registrar_usuario, name='registrar_usuario'),
    path('usuario/login/', login_, name='login_user'),
    path('usuario/logout/', logout_, name='logout_user')
]

MODULO 2/djangop/loanapp/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields.related import OneToOneField
from django.contrib.auth.models import User
# Create your models here.

class persona(models.Model):
    usuario = models.CharField(max_length=20, default='')
    email=models.EmailField(max_length=30, default='')
    contraseña = models.CharField(max_length=20, default='')
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=60)


class usuarios(models.Model):
    usuario = models.CharField(max_length=20, default='')
    contraseña = models.CharField(max_length=20, default='')

MODULO 2/djangop/loanapp/forms.py
from django.forms import EmailInput, PasswordInput, TextInput, ModelForm
from loanapp.models import *
from django import forms

class UsuarioForm(forms.Form):
    usuario = forms.CharField(max_length=30, widget=TextInput(attrs={
        'class':'form-control'
        }))
    nombres = forms.CharField(max_length=30, widget=TextInput(attrs={
        'class':'form-control'
    }))
    apellidos = forms.CharField(max_length=60, widget=TextInput(attrs={
        'class':'form-control'
    }))
    email = forms.CharField(max_length=60, widget=EmailInput(attrs={
        'class':'form-control',
        'placeholder':'nombre@correo'
    }))
    contraseña = forms.CharField(max_length=60, widget=PasswordInput(attrs={
        'class':'form-control'
    }))
    contraseña_verificar = forms.CharField(max_length=60, widget=PasswordInput(attrs={
    'class':'form-control'
    }))

class LoginForm(forms.Form):
    usuario = forms.CharField(max_length=30, widget=TextInput(attrs={
        'class':'form-control'
        }))
    contraseña = forms.CharField(max_length=60, widget=PasswordInput(attrs={
        'class':'form-control'
    }))

MODULO 2/djangop/loanapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, response
from datetime import datetime
from django.urls import reverse
from loanapp.models import *
from loanapp.forms import *
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'index.html')

def login_(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data['usuario']
            contraseña = form.cleaned_data['contraseña']
            user = authenticate(username=usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return redirect(reverse('home'))
            else:
                messages.warning(request, 'El usuario y/o contraseña es incorrecto')
                return redirect(reverse('login_user'))
        else:
            messages.warning(request, 'Error al leer los datos enviados')
            return redirect(reverse('login_user'))            
    else:
        contexto = dict()
        contexto['formLogin'] = LoginForm()
        return render(request, 'login_usuario.html', contexto)

def registrar_usuario(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data['usuario']
            email = form.cleaned_data['email']
            contraseña = form.cleaned_data['contraseña']
            contraseña_verificar = form.cleaned_data['contraseña_verificar']
            nombres = form.cleaned_data['nombres']
            apellidos = form.cleaned_data['apellidos']
            if contraseña == contraseña_verificar:
                User.objects.create_user(usuario, email, contraseña)
                messages.success(request, 'Usuario creado correctamente.')
                return redirect(reverse('registrar_usuario'))
            else:
                messages.warning(request, 'Contraseña no coincide')
                return redirect(reverse('registrar_usuario'))            
        else:
            messages.warning(request, 'Datos no validos')
            return redirect(reverse('registrar_usuario')) 
    else:      
        contexto = dict()
        contexto['UsuarioForm'] = UsuarioForm()
        return render(request, 'registrar_usuario.html', contexto)

@login_required(login_url='/usuario/login/')
def logout_(request):
    logout(request)
    return redirect(reverse('inicio'))

MODULO 2/djangop/loanapp/templates/correcto.html
<h4>Los datos han sido almacenados correctamente</h4>

<p>
    
    {% for dato in persona %}
        <p><strong>Usuario</strong>: {{dato.usuario}}</p>
        <p><strong>Contraseña</strong>: {{dato.contraseña}}</p>
    {% endfor %}
        
</p>

MODULO 2/djangop/loanapp/templates/fallo.html
<h4>Problema para guardar los datos correctamente</h4>

<p>
    No fue posible guardar los datos {{error}}
</p>

MODULO 2/djangop/loanapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="keywords" content="cosmetica,Cosmetica,belleza,Belleza,kosmetik,Kosmetik,beauty,Beauty,store,Suiza,Zurich">
		<meta name="description" content="Salon de belleza y cosmetica en Zurixh, Suiza">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block titulo %}Inicio{% endblock titulo %} | Francys Beauty Kosmetik</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<link rel="shortcut icon" href="{% static 'favicon.ico' %}">
		<link rel="preconnect" href="https://fonts.gstatic.com">
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'normalize.css'%}">
		<link rel="stylesheet" href="{%static 'styles.css'%} ">
		<script src="https://kit.fontawesome.com/a9b00b0f2d.js" crossorigin="anonymous"></script>
	</head>
	<body>
		<header>
			<div class="container mx-0 w-100">
				<a href="{% url 'home' %}">
					<img src="{% static 'logofbk.svg'%}" class="logo">
				</a>
				<nav>
					<a href="{% url 'home' %}">Inicio</a>
					<a href="#nosotros">Especialista</a>
					<a href="#servicios">Servicios</a>
					<a href="#galeria">Galería</a>
					<a href="#catalogo">Catalogo</a>
					<a href="#seccion">Contactar</a>
					<a href="{% url 'login_user' %}">Acceder</a>
					<a href="{%url 'registrar_usuario'%}">Registrar</a>
				</nav>
				<a href="#" class="hamb"><i class="fas fa-bars"></i></a>
			</div>
		</header>
		{% block contenido %}
		<section id="inicio">
				<div class="bloque-inicio">
					<h1>Bienvenidos a Francys Beauty Kosmetik</h1>
					<p>
								Cosmetologa diplomada en Colombia y Suiza
					</p>
					<a href="#nosotros" class="boton boton-rosa">Ver más</a>
				</div>
			</section>
			<br>
			<section id="nosotros">
				<div class="container">
					<p id="namef">Francy Baier</p>
					<hr>
					<div class="cos">
						<div class="cuadrado-foto">
							<img src="{% static 'fd.png'%}">
						</div>
						<div class="info">
							<p>
										
									<br>Especialista en tecnicas manuales faciales y corporales, reducción y moldeo.
									<br>Certificada en manejo de paciente pre y posquirurgico.
												<br>Drenaje linfático, Micropigmentadora.
									<br>Especialista en maderoterapia y metaloterapía técnica colombiana
												<br>Maquilladora profesional
													<br>Diseñadora de uñas
												<br>Experta en depilación
							</p>
						</div>
					</div>
				</div>
			</section>
			<section id="servicios" class="seccion">
				<div class="container">
					<div class="row">
						<div class="columna columna-33 columna-mobile-100">
							<div class="bloque-servicio">
								<div class="bloque-img-servicio cuadrado-perfecto">
									<img src="{% static 'fe.jpg'%}">
								</div>
								<div class="bloque-contenido-servicio">
									<h3>Maquillajes</h3>
									<p>Hay una gran variedad de Maquillajes</p>
									<a href="#catalogo" class="boton boton-rosado">Ver más</a>
								</div>
							</div>
						</div>
						<div class="columna columna-33 columna-mobile-100">
							<div class="bloque-servicio">
								<div class="bloque-img-servicio cuadrado-perfecto">
									<img src="{% static 'fb.jpg'%}">
								</div>
								<div class="bloque-contenido-servicio">
									<h3>Tratamientos</h3>
									<p>Hay una gran variedad de Tratamientos</p>
									<a href="#catalogo" class="boton boton-rosado">Ver más</a>
								</div>
							</div>
						</div>
						<div class="columna columna-33 columna-mobile-100">
							<div class="bloque-servicio">
								<div class="bloque-img-servicio cuadrado-perfecto">
									<img src="{% static 'fc.jpg'%}">
								</div>
								<div class="bloque-contenido-servicio">
									<h3>Terapias</h3>
									<p>Hay una gran variedad de Terapias</p>
									<a href="#catalogo" class="boton boton-rosado">Ver más</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<section id="galeria">
				<div class="container-fluid">
				<div class="row">
					<div class="columna-33 columna-mobile-50 px-0">
						<div class="cuadrado-perfecto">
							<img src="{% static 'fu.jpg'%}">

						</div>
					</div>
					<div class="columna-33 columna-mobile-50 px-0">
						<div class="cuadrado-perfecto">
							<img src="{% static 'fo.jpg'%}">

						</div>
					</div>
					<div class="columna-33 columna-mobile-50 px-0">
						<div class="cuadrado-perfecto">
							<img src="{% static 'fr.jpg' %}">
						</div>
					</div>
					<div class="columna-33 columna-mobile-50 px-0">
						<div class="cuadrado-perfecto">
							<img src="{% static 'fm.jpg' %}">
						</div>
					</div>
					<div class="columna-33 columna-mobile-50 px-0">
						<div class="cuadrado-perfecto">
							<img src="{% static 'fl.jpg' %}">
						</div>
					</div>
					<div class="columna-33 columna-mobile-50 px-0">
						<div class="cuadrado-perfecto">
							<img id="img1" src="{% static 'fg.jpg' %}">
						</div>
					</div>
				</div>
			</div>
			</section>
			<br>
			<section id="catalogo">
				<div class="container-fluid-ca align-items-center pr-20">
					<div class="cuadrado-catalogo">
						<img id="img1" src="{% static 'p1.png' %}">
					</div>
					<div class="cuadrado-catalogo">
						<img id="img2" src="{% static 'p2.png' %}">
					</div>
				</div>
			</section>	
			<br>				
				{% endblock contenido %}	
		<footer class="seccion" id="seccion">
			<div class="container">
				<div class="row">
					<div class="columna-25 columna-mobile-100">
						<img src="{% static 'logofbk.svg' %}" class="logo-footer">
						<p>
							Brindamos servicios con calidad e integridad. 
						</p>
					</div>
					<div class="columna-25 columna-mobile-100">
						<h3>
							Datos de contacto
						</h3>
						<ul>
							<li>francy81-mosquera@hotmail.com</li>
							<li>+076 722 0271</li>
							<li>Klotenerstrasse 15<br>CH-8304 Walliseller/Zürich/Scheiz</li>
						</ul>
					</div>
					<div class="columna-25 columna-mobile-100">
						<h3>
							Redes Sociales
						</h3>
						<ul class="redes">
							<li>
								<a href="https://www.facebook.com/francy.baier">
									<i class="fab fa-facebook-square"></i>
								</a>
							</li>
							<li>
								<a href="https://www.instagram.com/kosmetikerinfrancys/?hl=es">
									<i class="fab fa-instagram-square"></i>
								</a>
							</li>
							<li>
								<a href="https://www.tiktok.com/@cosmetologa81?">
									<i class="fab fa-tiktok"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="barra-footer">
				&copy; Derechos Reservados - 2021
			</div>
		</footer>
		<script src="{% static 'jquery.js' %}"></script>
		<script src="{% static 'funcions.js' %}"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	</body>
</html>

MODULO 2/djangop/loanapp/templates/login_usuario.html
{% extends 'index.html' %}

{% block titulo %}
    Acceso
{% endblock titulo %}

{% block tema %}
    Acceso                           
{% endblock tema %}

{% block contenido %}
<br>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h6>Acceder al Sitio | Login</h6>
                </div>
                <div class="card-body">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                    
                {% endif %}
                    <form action="{% url 'login_user' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_usuario" class="form-label">{{formLogin.usuario.label}}</label>
                            {{formLogin.usuario}}                         
                        </div>
                        <div class="mb-3">
                            <label for="id_contraseña" class="form-label">{{formLogin.contraseña.label}}</label>
                            {{formLogin.contraseña}}
                        </div>                        
                        <button type="submit" class="btn btn-primary">Ingresar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<br>      
<div style="padding-left: 42px ">
    <p>Si no tiene su usuario/contraseña <a href="{%url 'registrar_usuario'%}"><b> Registrarse</b></a></p> 
</div>  
<br>              
{% endblock contenido %}

MODULO 2/djangop/loanapp/templates/registrar_usuario.html
{% extends 'index.html' %}

{% block titulo %}
    Registro
{% endblock titulo %}

{% block tema %}
    Agregar Usuario                            
{% endblock tema %}

{% block contenido %}
<br>
<div class="row">
    <div class="col-6">
        <form action="{% url 'registrar_usuario' %}" method="post"> 
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                
            {% endif %}          
            {% csrf_token %}            
            <div class="row mb-3">
                {{UsuarioForm.usuario.label}}
                {{UsuarioForm.usuario}}
            </div>
            <div class="row mb-3">
                {{UsuarioForm.email.label}}
                {{UsuarioForm.email}}
            </div>
            <div class="row mb-3">
                {{UsuarioForm.contraseña.label}}
                {{UsuarioForm.contraseña}}
            </div>
            <div class="row mb-3">
                {{UsuarioForm.contraseña_verificar.label}}
                {{UsuarioForm.contraseña_verificar}}
            </div> 
            <div class="row m-1">
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">Registrar</button>                    
                </div>
                <div class="col-2">
                    <button type="reset" class="btn btn-secondary">Resetear</button>
                </div>                
            </div>        
        </form>        
    </div>
</div>
<br> 
<div style="padding-left: 42px ">
<p>Si ya tiene su usuario/contraseña <a href="{%url 'login_user'%}"><b>Iniciar Sesión</b></a></p> 
</div>
<br>                   
{% endblock contenido %}

MODULO 2/djangop/loanapp/templates/respuesta.html
{% extends 'index.html' %}


{% block contenido %}
    
    {% if estado ==True %}
        {%include 'correcto.html'%}
    {% else %}
        {%include 'fallo.html'%}
    {% endif %}
        
{% endblock contenido %}
    